[package]
name = "server"
version = "0.1.0-beta"
edition = "2024"

[dependencies]
tonic = { version = "0.11", features = ["transport"] }
tokio = { version = "1", features = ["full"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
